version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: keredonaiwakatachiniuta
      MYSQL_DATABASE: mealu
      TZ: Asia/Seoul
      MYSQL_USER: HeXA
      MYSQL_PASSWORD: dkdlrhdiwhfflekwjdakf
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci