version: v0.0.1
server:
  port: 8282
logging:
  pattern:
    dateformat: yyyy-MM-dd
    file: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative] %-5level ${PID:-} --- [%15.15thread] %-40.40logger{36} : %msg%n"
    console: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative]  %clr(%-5level) %clr(${PID:-}){magenta} %clr(---){faint} %clr([%15.15thread]){faint} %clr(%-40.40logger{36}){cyan} %clr(:){faint} %msg%n"
  file:
    name: logs/unistMeal.log
  logback:
    rollingpolicy:
      file-name-pattern: ./was-logs/info.%d{yyyy-MM-dd}.%i.log.gz
      max-history: 180
      max-file-size: 100MB
---
spring:
  config:
    activate:
      on-profile: default, development
secretKey: someUpdateKeyToChangeWhereYouWantToChangeMenu
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://localhost:3306/mealu
    username: root
    password: keredonaiwakatachiniuta
secretKey: someUpdateKeyToChangeWhereYouWantToChangeMenu
---
spring:
  profiles:
    active: production