version: v0.0.1
server:
  port: 1174
logging:
  pattern:
    dateformat: yyyy-MM-dd
    file: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative] %-5level ${PID:-} --- [%15.15thread] %-40.40logger{36} : %msg%n"
    console: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative]  %clr(%-5level) %clr(${PID:-}){magenta} %clr(---){faint} %clr([%15.15thread]){faint} %clr(%-40.40logger{36}){cyan} %clr(:){faint} %msg%n"
  file:
    name: logs/unistMeal.log
  logback:
    rollingpolicy:
      file-name-pattern: ./was-logs/info.%d{yyyy-MM-dd}.%i.log.gz
      max-history: 180
      max-file-size: 100MB
---
spring:
  config:
    activate:
      on-profile: default, development
    import: optional:file:.env[.properties]
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
---
spring:
  profiles:
    active: production